version: "3.8"
services:
  investment:
    image: investment
    container_name: investment
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3070:3070"
    environment:
      - NODE_ENV=production